FROM gcr.io/self-serve-dev-261801/docs-v1:base AS base

WORKDIR /opt/services/docs-v1/

COPY . .

COPY gitconfigfile .git/config

RUN git submodule update docs/

RUN cd docs/ && git config user.email "service-account@symbl.ai" && git config  user.name "service-account" && git checkout develop &&  git pull origin develop && cd .. && rm -rf node_modules && npm i

RUN rm -rf src/theme/DocPage

RUN npm audit fix

RUN npm run build-staging

RUN mkdir docs-build && mv build docs-build && mv docs-build build && mv build/build build/docs

FROM nginx:alpine

RUN apk update && apk del curl && apk add curl-doc && apk --no-cache add curl

COPY default-dev /etc/nginx/conf.d/default.conf

COPY --chown=0:0 --from=base /opt/services/docs-v1 /opt/services/docs-v1

EXPOSE 80

